"""empty message

Revision ID: bb5cf4489b10
Revises: 899c0d963d0b
Create Date: 2024-11-11 23:47:33.637548

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb5cf4489b10"
down_revision = "899c0d963d0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=200), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
